# Generated by Django 5.0.4 on 2024-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('duracion', models.IntegerField()),
                ('descripcion',models.CharField(max_length=100)),
                ('actores',models.CharField(max_length=40)),
                ('directores',models.CharField(max_length=40)),
            ],
        ),
    ]
